gui:
  commandLogSize: 20
  theme:
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red       # Red
