export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/bin:~/.composer/vendor/bin:$PATH
export PATH="/opt/homebrew/bin:$PATH"
export XDG_CONFIG_HOME=$HOME/.config

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="jnrowe"

plugins=(
	git
	z
	brew
	zsh-autosuggestions
	dirhistory
	fzf
	tmux
	rbenv
	tmux
)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
else
	export EDITOR='nvim'
fi


alias zshconfig="nvim ~/.dotfiles/zsh/zshrc"
alias ohmyzsh="cd ~/.oh-my-zsh"
alias vi="nvim"
alias refrezsh="source ~/.zshrc"
alias gitpretty="git log --all --decorate --oneline --graph"
alias oldbrew="arm /usr/local/bin/brew"
alias ls="lsd"

nah() {
	git reset --hard
	git clean -df
	if [ -d ".git/rebase-apply" ] || [ -d ".git/rebase-merge" ]; then
		git rebase --abort
	fi
}

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'

eval $(thefuck --alias)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


